# Workflow for building and deploying a React app to GitHub Pages
name: Deploy React App to Pages

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 1: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x # Use a current LTS version
          cache: "npm"

      # Step 2: Install dependencies
      # Using 'npm ci' is recommended for workflows for faster, reliable installs
      - name: Install dependencies
        run: npm i yarn

      # Step 3: Test the React application
      # Using 'yarn test' to run the tests
      - name: Testing
        run: yarn test

      # Step 4: Build the React application
      # This assumes your build script is 'npm run build'
      - name: Build
        run: yarn build

      # Step 5: Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 6: Upload the build artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the 'dist' directory (or 'build' if you use Create React App)
          path: "./dist"

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
